### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by mdere** [go-pg/pg#778]
Hello - So I am a little new to Golang, but actively trying to learn how to create a webapp. So I ran across this library and I am trying to create a library that all my micro services would use - so this is my connection function:

```
package rdbms
// Connect connects to a RDBMS instance
func Connect(serviceName string) *pg.DB {
    log.Log("Connecting " + serviceName + " to the RDBMS DataBase...")
    db := pg.Connect(&pg.Options{
        User: "postgres",
        Password: "secret",
        Database: "test_db",
    })
    log.Log("Sucessfully connected " + serviceName + " to RDBMS Database")
    return db
}
```

Then in my services I import this package and do
```
var db = rdbms.Connect("user.service")

type User struct{
    Email string
    Firstname string
    Lastname string
}

func Register(.....) {
  user := &User{...........}
  err := db.Insert(user)
}
```

I get a `dial tcp 127.0.0.1:5432: getsockopt: connection refused`

So I am using Docker-Compose to run my app:

```
rdbms:
  image: postgres:10.2
  container_name: "test_postgres_db"
  restart: always
  environment:
    - POSTGRES_DB=test_db
    - POSTGRES_PASSWORD=secret
  ports:
    - "5432:5432"
......
```

I am not sure what I am doing wrong here...any help or direction I would gladly appreciate!
